#!/usr/bin/env python3
"""
Generate skill index for GradAgentKit.

This script scans the skills directory and generates docs/skill-index.md.

Usage:
    python scripts/generate-skill-index.py

Output:
    docs/skill-index.md
"""

import os
import sys
from pathlib import Path


def get_skills_directory():
    """Get the skills directory path."""
    script_dir = Path(__file__).parent
    project_dir = script_dir.parent
    skills_dir = project_dir / 'skills'
    return skills_dir


def get_docs_directory():
    """Get the docs directory path."""
    script_dir = Path(__file__).parent
    project_dir = script_dir.parent
    docs_dir = project_dir / 'docs'
    return docs_dir


def extract_skill_info(skill_dir):
    """
    Extract information from a skill directory.

    Args:
        skill_dir: Path to the skill directory

    Returns:
        dict: Skill information
    """
    skill_name = skill_dir.name
    skill_md_path = skill_dir / 'SKILL.md'

    info = {
        'name': skill_name,
        'description': '',
        'use_when': [],
        'path': f'skills/{skill_name}/',
    }

    # Read SKILL.md to extract description
    if skill_md_path.exists():
        try:
            with open(skill_md_path, 'r', encoding='utf-8') as f:
                content = f.read()

            # Extract description (first paragraph after title)
            lines = content.split('\n')
            in_description = False
            description_lines = []

            for line in lines:
                if line.startswith('# ') and not in_description:
                    in_description = True
                    continue

                if in_description:
                    if line.strip() == '':
                        if description_lines:
                            break
                        continue

                    if line.startswith('##'):
                        break

                    description_lines.append(line.strip())

            if description_lines:
                info['description'] = ' '.join(description_lines)

            # Extract "When to Use" section
            in_when_to_use = False
            when_lines = []

            for line in lines:
                if '## When to Use' in line:
                    in_when_to_use = True
                    continue

                if in_when_to_use:
                    if line.startswith('##'):
                        break

                    if line.strip().startswith('- '):
                        when_lines.append(line.strip()[2:])

            info['use_when'] = when_lines

        except Exception as e:
            print(f"⚠️  Error reading {skill_md_path}: {e}")

    return info


def generate_skill_index(skills_info):
    """
    Generate skill index markdown content.

    Args:
        skills_info: List of skill information dicts

    Returns:
        str: Markdown content
    """
    content = """# Skill Index

> Auto-generated index of all GradAgentKit skills.

---

## Overview

GradAgentKit provides the following skills:

| Skill | Description | Use When |
|-------|-------------|----------|
"""

    for skill in skills_info:
        name = skill['name']
        description = skill['description'][:50] + '...' if len(skill['description']) > 50 else skill['description']
        use_when = ', '.join(skill['use_when'][:2]) if skill['use_when'] else 'N/A'
        path = skill['path']

        content += f"| [{name}]({path}) | {description} | {use_when} |\n"

    content += """
---

## Skills Details

"""

    for skill in skills_info:
        name = skill['name']
        description = skill['description']
        path = skill['path']
        use_when = skill['use_when']

        content += f"""### {name}

**Path**: `{path}`

**Description**: {description}

**Use When**:
"""

        if use_when:
            for item in use_when:
                content += f"- {item}\n"
        else:
            content += "- See SKILL.md for details\n"

        content += "\n"

    content += """---

## Installation

```bash
# Copy all skills
cp -r skills/* your-project/.claude/skills/

# Copy specific skill
cp -r skills/paper-writer your-project/.claude/skills/
```

---

## Usage

```markdown
# In your Claude Code session:

Use the [skill-name] skill to [accomplish task].
```

---

*Auto-generated by generate-skill-index.py*
"""

    return content


def main():
    """Main function."""
    skills_dir = get_skills_directory()
    docs_dir = get_docs_directory()

    if not skills_dir.exists():
        print(f"❌ Skills directory not found: {skills_dir}")
        sys.exit(1)

    # Get all skill directories
    skill_dirs = [d for d in skills_dir.iterdir() if d.is_dir()]

    if not skill_dirs:
        print("⚠️  No skills found in skills directory")
        sys.exit(0)

    # Extract information from each skill
    skills_info = []

    print("🔍 Scanning skills...\n")

    for skill_dir in sorted(skill_dirs):
        skill_name = skill_dir.name

        # Skip hidden directories
        if skill_name.startswith('.'):
            continue

        print(f"   Reading {skill_name}...")
        info = extract_skill_info(skill_dir)
        skills_info.append(info)

    # Generate index
    print(f"\n📝 Generating skill index...")
    index_content = generate_skill_index(skills_info)

    # Write to docs/skill-index.md
    docs_dir.mkdir(exist_ok=True)
    index_path = docs_dir / 'skill-index.md'

    try:
        with open(index_path, 'w', encoding='utf-8') as f:
            f.write(index_content)

        print(f"✅ Skill index generated: {index_path}")
        print(f"   Found {len(skills_info)} skills")

    except Exception as e:
        print(f"❌ Error writing {index_path}: {e}")
        sys.exit(1)


if __name__ == '__main__':
    main()